/**
 * Cross-chat references: pointing one conversation at another.
 *
 * Asked for as "Devin lets me link a thread so another agent can read it".
 * A desktop app has no URLs, so the reference is the chat's own row id,
 * rendered as `[[chat:<id>]]` — a token that survives a clipboard, a note, a
 * skill file and a composer, and that the app can turn back into navigation.
 *
 * WHY THE REFERENCE CARRIES NO CONTENT
 * ------------------------------------
 * A reference states that another thread is relevant and stops there. The
 * agent then reads it through `mcp__chats__read_chat`, or does not, depending
 * on whether the message it is attached to turns out to need it. The
 * alternative — splicing the other thread's text into the outgoing message —
 * was rejected for a measured reason, not a stylistic one: every turn of a
 * chat resumes the same transcript, so text inlined once is re-sent for the
 * life of the thread. That is precisely how a single 39,335-row CSV produced a
 * 5.5 MB transcript and left a chat permanently answering "Prompt is too long"
 * to a bare "Hi" (see the 2026-07-28 entry in CLAUDE.md). An id costs ~40
 * characters per turn forever; a thread costs tens of thousands.
 *
 * This module is the single source of truth for the three things the renderer,
 * main and the persisted row must agree on: the wire format of a reference,
 * how a reference is announced to the agent, and how a stored reference is
 * read back. It is the sibling of `shared/quotes.ts` and deliberately mirrors
 * its shape — a chip above the composer, its own field on the turn, composed
 * into the outgoing text in exactly one place.
 */

/**
 * A reference after main has tried to resolve it against the database.
 *
 * Unresolved cases are carried rather than dropped, and that is the whole
 * reason this type has three fields instead of two. A reference to a deleted
 * chat that is silently omitted leaves the model reading a message that
 * gestures at context it was never given — the most likely outcome being that
 * it answers from the surrounding sentence and sounds confident. Saying "that
 * chat no longer exists" costs one line and forecloses it.
 */
export interface AcaboxChatRef {
  /** Full `sessions.id` when resolved; whatever the user wrote when not. */
  sessionId: string;
  /** The chat's current title. Empty when unresolved. */
  title: string;
  /** Why this reference does not name exactly one chat. */
  unresolved?: 'not_found' | 'ambiguous';
  /** Full ids that matched, when the written prefix was ambiguous. */
  candidates?: string[];
}

/**
 * Characters of the id used in a written reference.
 *
 * A full `randomUUID()` is 36 characters and makes `[[chat:…]]` a 45-character
 * eyesore in a composer someone is typing a sentence into. Eight hex
 * characters is 4.3 billion values against a chat count in the tens, so a
 * collision is not a practical concern — and when one does occur it is
 * reported rather than guessed at, which is why the short form is safe to
 * prefer over a truncation that could silently resolve to the wrong thread.
 */
export const CHAT_REF_ID_CHARS = 8;

/** Does a full session id match a written (possibly shortened) reference? */
export function chatIdMatchesRef(sessionId: string, written: string): boolean {
  return sessionId.toLowerCase().startsWith(written.toLowerCase());
}

/**
 * Ceiling on references per message.
 *
 * Not a guardrail against carelessness: each reference is an invitation to
 * read a whole other thread, and a turn that opens six of them can exhaust a
 * context window on retrieval before answering anything. Five is well past
 * what a real question needs and still bounded.
 */
export const MAX_CHAT_REFS_PER_MESSAGE = 5;

/** Longest title we will render or send, so a pathological title cannot itself
 *  become the payload. */
const MAX_TITLE_CHARS = 120;

/**
 * The pasteable form of a reference.
 *
 * Double brackets rather than a URL scheme: `acabox://chat/<id>` looks like
 * something a browser should open and is mangled by every autolinker it
 * touches, while `[[…]]` is inert everywhere, already means "internal link" to
 * anyone who has used a wiki or Obsidian, and survives markdown rendering
 * untouched.
 */
export function formatChatRef(sessionId: string): string {
  return `[[chat:${sessionId.slice(0, CHAT_REF_ID_CHARS)}]]`;
}

/**
 * Matches a reference token. Deliberately narrow — ids are generated by
 * `randomUUID()`, so anything outside the hex/dash alphabet is not one of ours
 * and must not be silently treated as a chat id. The length ceiling keeps a
 * pathological document from turning this into a scanning cost.
 */
const CHAT_REF_RE = /\[\[chat:([A-Za-z0-9][A-Za-z0-9._-]{0,127})\]\]/g;

/**
 * Split text into plain runs and the references embedded in it, so a renderer
 * can turn each reference into something clickable while leaving the rest of
 * the prose alone.
 *
 * Lives beside the pattern it depends on rather than in the renderer: the
 * token's grammar is defined once here, and a second regex maintained next to
 * a component is how a reference starts rendering in one place and not the
 * other.
 */
export type ChatRefSegment = { kind: 'text'; text: string } | { kind: 'ref'; written: string };

export function splitOnChatRefs(text: string): ChatRefSegment[] {
  if (!text || !text.includes('[[chat:')) return [{ kind: 'text', text }];
  const out: ChatRefSegment[] = [];
  let last = 0;
  for (const match of text.matchAll(CHAT_REF_RE)) {
    const start = match.index ?? 0;
    if (start > last) out.push({ kind: 'text', text: text.slice(last, start) });
    out.push({ kind: 'ref', written: match[1] });
    last = start + match[0].length;
  }
  if (last < text.length) out.push({ kind: 'text', text: text.slice(last) });
  return out;
}

/** Every chat id referenced in a block of text, in order, without duplicates. */
export function parseChatRefs(text: string): string[] {
  if (!text) return [];
  const seen = new Set<string>();
  const out: string[] = [];
  for (const match of text.matchAll(CHAT_REF_RE)) {
    const id = match[1];
    if (!seen.has(id)) {
      seen.add(id);
      out.push(id);
    }
  }
  return out;
}

function shortTitle(title: string): string {
  const clean = title.replace(/\s+/g, ' ').trim();
  if (!clean) return 'Untitled chat';
  return clean.length > MAX_TITLE_CHARS ? `${clean.slice(0, MAX_TITLE_CHARS - 1)}…` : clean;
}

/**
 * Build the text the agent receives.
 *
 * One line per reference, above whatever the user typed. The wording is doing
 * real work and is the whole of the "on demand" decision:
 *
 *  - It names the tool, because a model that knows a thread exists but not how
 *    to open it will either guess at a tool name or, worse, answer from the
 *    title alone.
 *  - It says "if it bears on this message", because the user attaching a
 *    reference is saying "this might be relevant", not "read this first". A
 *    follow-up like "thanks" must not trigger a 15,000-token retrieval.
 *  - It states that the content is NOT included, because otherwise the most
 *    likely failure is a model that assumes the excerpt is already in context
 *    and confabulates from the title.
 *
 * Pure, and the only place composition happens: main calls it on the way to
 * the agent while persisting the typed text untouched, so what is stored and
 * what is sent cannot drift into two implementations. Mirrors
 * `composeQuotedText` in `shared/quotes.ts`, including the no-op-on-empty
 * behaviour that keeps the ordinary path unchanged.
 */
export function composeChatRefText(
  refs: AcaboxChatRef[] | undefined | null,
  typed: string,
): string {
  if (!refs || refs.length === 0) return typed;
  const capped = refs.slice(0, MAX_CHAT_REFS_PER_MESSAGE);

  const lines = capped.map((ref) => {
    if (ref.unresolved === 'not_found') {
      return `[Referenced chat id ${ref.sessionId}: no chat with that id exists any more — `
        + 'it was probably deleted. Do not guess at what it contained; say so if it mattered.]';
    }
    if (ref.unresolved === 'ambiguous') {
      return `[Referenced chat id ${ref.sessionId} matches more than one chat `
        + `(${(ref.candidates ?? []).join(', ')}). Ask which one was meant, or use search_chats.]`;
    }
    return `[Referenced chat: "${shortTitle(ref.title)}" (id: ${ref.sessionId}). `
      + 'Its contents are NOT included here — call the read_chat tool with that id '
      + 'if it bears on this message.]';
  });

  const typedPart = typed.trim();
  const header = lines.join('\n');
  return typedPart ? `${header}\n\n${typedPart}` : header;
}

/**
 * Defensive parse for references read back out of SQLite or off the IPC
 * boundary. Both are places where the value may have been written by an older
 * build, so anything malformed degrades to "this message has no references"
 * rather than throwing inside a history render.
 */
export function parseStoredChatRefs(value: unknown): AcaboxChatRef[] | undefined {
  if (!Array.isArray(value)) return undefined;
  const out: AcaboxChatRef[] = [];
  for (const entry of value) {
    if (!entry || typeof entry !== 'object') continue;
    const ref = entry as Partial<AcaboxChatRef>;
    if (typeof ref.sessionId !== 'string' || !ref.sessionId) continue;
    out.push({
      sessionId: ref.sessionId,
      title: typeof ref.title === 'string' && ref.title ? ref.title : 'Untitled chat',
    });
    if (out.length >= MAX_CHAT_REFS_PER_MESSAGE) break;
  }
  return out.length ? out : undefined;
}
