import React from 'react';
import { ReviewSuggestion } from '../services/projectsApi';

interface ReviewComponentProps {
  review: ReviewSuggestion;
  onAccept?: () => void;
  onReject?: () => void;
}

const ReviewComponent: React.FC<ReviewComponentProps> = ({ review }) => {
  console.log('[ReviewComponent] Rendering review:', review);

  const getTypeColor = (type: string | undefined): string => {
    if (!type) return '#6c757d';
    const colors: Record<string, string> = {
      strength: '#28a745',
      weakness: '#dc3545',
      suggestion: '#0645b1',
      question: '#ffc107',
    };
    return colors[type.toLowerCase()] || '#6c757d';
  };

  const getTypeLabel = (type: string | undefined): string => {
    if (!type) return 'Review';
    return type.charAt(0).toUpperCase() + type.slice(1);
  };

  return (
    <div className="reviewComponent">
      <div className="reviewHeader">
        <span
          className="reviewType"
          style={{ backgroundColor: getTypeColor(review.review_item_type) }}
        >
          {getTypeLabel(review.review_item_type)}
        </span>
        {review.priority && (
          <span className="reviewPriorityBadge">High Priority</span>
        )}
      </div>

      {review.title && (
        <div className="reviewTitle">
          <h3>{review.title}</h3>
        </div>
      )}

      {review.critique && (
        <div className="reviewCritique">
          <div
            dangerouslySetInnerHTML={{ __html: review.critique }}
          />
        </div>
      )}

      {review.framework_to_address && (
        <div className="reviewFramework">
          <div className="reviewFrameworkLabel">Suggested Framework to Address:</div>
          <div
            dangerouslySetInnerHTML={{ __html: review.framework_to_address }}
          />
        </div>
      )}

      {review.llm_model && (
        <div className="reviewMeta">
          <span className="reviewMetaLabel">Generated by:</span> {review.llm_model}
        </div>
      )}
    </div>
  );
};

export default ReviewComponent;
