/**
 * macOS bundle-swap self-updater.
 *
 * WHY THIS EXISTS: Squirrel.Mac validates a downloaded update against the
 * *running* app's designated requirement. Acabox is ad-hoc signed, so its DR is
 * `cdhash H"…"` — a hash of one specific build — and no future build can ever
 * satisfy it. Confirmed in the wild (2026-07-27, v0.1.1 → v0.1.2):
 *
 *   Code signature at URL file:///…/com.electron.acabox.ShipIt/update.wdWeDhW/
 *   Acabox.app/ did not pass validation: code failed to satisfy specified code
 *   requirement(s)
 *
 * There is no bypass — the check lives inside Squirrel's ShipIt binary, and
 * electron-updater exposes no option for it on macOS.
 *
 * So: electron-updater still does DETECTION (which works — it reads
 * `latest-mac.yml` off the GitHub release and compares versions), and we do the
 * install ourselves. Download the zip the manifest names, verify the manifest's
 * sha512, unpack it beside the installed bundle, then hand a detached shell
 * script the job of swapping the two once this process has exited.
 *
 * Integrity rests on that sha512, fetched over TLS from the release — a
 * strictly stronger guarantee than the ad-hoc signature Squirrel was checking,
 * which only ever proved "signed by nobody in particular".
 *
 * DELETE THIS MODULE once the app has a Developer ID: plain Squirrel is better
 * maintained than anything hand-rolled here. See the auto-update entry in
 * CLAUDE.md for what that switch involves.
 */

import { app, net } from 'electron';
import { constants as fsConstants, createWriteStream, promises as fsp } from 'fs';
import { createHash } from 'crypto';
import { execFile, spawn } from 'child_process';
import { promisify } from 'util';
import { once } from 'events';
import path from 'path';
import os from 'os';
import log from 'electron-log';

const execFileAsync = promisify(execFile);

/** One entry of `latest-mac.yml`'s `files:` list. */
export interface UpdateFileInfo {
  url: string;
  sha512: string;
  size?: number;
}

export interface SelfUpdateRequest {
  version: string;
  files: UpdateFileInfo[];
  owner: string;
  repo: string;
  onProgress: (percent: number) => void;
}

/**
 * The installed `.app` bundle we are running from, or null if we can't find one
 * (dev mode, or an unusual layout).
 */
function resolveInstalledBundle(): string | null {
  // /Applications/Acabox.app/Contents/MacOS/Acabox  ->  /Applications/Acabox.app
  const exe = app.getPath('exe');
  const marker = `${path.sep}Contents${path.sep}MacOS${path.sep}`;
  const idx = exe.indexOf(marker);
  if (idx === -1) return null;
  const bundle = exe.slice(0, idx);
  return bundle.endsWith('.app') ? bundle : null;
}

export interface SelfUpdateSupport {
  ok: boolean;
  reason?: string;
  bundlePath?: string;
}

/**
 * Can we actually perform a swap? Checked up front so a failure is reported
 * before a 180MB download rather than after it.
 */
export async function checkSelfUpdateSupported(): Promise<SelfUpdateSupport> {
  if (process.platform !== 'darwin') {
    return { ok: false, reason: 'Self-update is implemented for macOS only.' };
  }
  if (!app.isPackaged) {
    return { ok: false, reason: 'Self-update is disabled in development.' };
  }

  const bundlePath = resolveInstalledBundle();
  if (!bundlePath) {
    return { ok: false, reason: 'Could not locate the installed application bundle.' };
  }
  // Gatekeeper path randomization: a quarantined app run from Downloads or a
  // mounted dmg executes from a read-only shadow copy. Swapping that would
  // update a throwaway directory and silently do nothing.
  if (bundlePath.includes('/AppTranslocation/')) {
    return {
      ok: false,
      reason: 'Acabox is running from a temporary location. Move it to /Applications and reopen it.',
    };
  }

  // We move the bundle aside and move a new one in, so it's the PARENT that
  // needs to be writable, not the bundle.
  const parent = path.dirname(bundlePath);
  try {
    await fsp.access(parent, fsConstants.W_OK);
  } catch {
    return { ok: false, reason: `No write permission for ${parent}.` };
  }

  return { ok: true, bundlePath };
}

/** Pick the zip for this architecture from the manifest's file list. */
function selectUpdateFile(files: UpdateFileInfo[]): UpdateFileInfo | null {
  const zips = files.filter((f) => f.url.endsWith('.zip'));
  if (zips.length === 0) return null;
  // Manifests generated by scripts/release.mjs carry exactly one arch. If a
  // future multi-arch release lists several, take ours rather than the first.
  return zips.find((f) => f.url.includes(process.arch)) ?? zips[0];
}

/**
 * Download to `destPath`, hashing as we go. Returns the base64 sha512, in the
 * same encoding electron-builder writes into the manifest.
 */
async function downloadWithProgress(
  url: string,
  destPath: string,
  expectedSize: number | undefined,
  onProgress: (percent: number) => void,
): Promise<string> {
  const res = await net.fetch(url);
  if (!res.ok) throw new Error(`Download failed: HTTP ${res.status} for ${url}`);
  if (!res.body) throw new Error('Download failed: response had no body.');

  const total = Number(res.headers.get('content-length')) || expectedSize || 0;
  const hash = createHash('sha512');
  const out = createWriteStream(destPath);
  const reader = res.body.getReader();

  let received = 0;
  let lastReport = 0;
  try {
    for (;;) {
      const { done, value } = await reader.read();
      if (done) break;
      hash.update(value);
      received += value.length;
      if (!out.write(value)) await once(out, 'drain');
      // Throttle: the renderer only draws a progress bar, and one IPC message
      // per 64KB chunk over ~180MB is ~2900 messages.
      const now = Date.now();
      if (total > 0 && now - lastReport > 200) {
        lastReport = now;
        onProgress(Math.min(100, (received / total) * 100));
      }
    }
  } finally {
    out.end();
  }
  await once(out, 'close');

  if (total > 0 && received !== total) {
    throw new Error(`Download truncated: got ${received} of ${total} bytes.`);
  }
  onProgress(100);
  return hash.digest('base64');
}

/** Read one key out of a bundle's Info.plist. */
async function readPlistValue(bundlePath: string, key: string): Promise<string | null> {
  try {
    const { stdout } = await execFileAsync('/usr/libexec/PlistBuddy', [
      '-c', `Print :${key}`,
      path.join(bundlePath, 'Contents', 'Info.plist'),
    ]);
    return stdout.trim();
  } catch {
    return null;
  }
}

/**
 * Everything Squirrel would have checked before trusting the payload, minus the
 * signature identity we can't have: it is the app we think it is, at the
 * version we think it is, and macOS considers its signature intact.
 */
async function validateNewBundle(newBundlePath: string, expectedVersion: string): Promise<void> {
  const stat = await fsp.stat(newBundlePath).catch(() => null);
  if (!stat?.isDirectory()) {
    throw new Error(`Unpacked update is missing ${path.basename(newBundlePath)}.`);
  }

  const bundleId = await readPlistValue(newBundlePath, 'CFBundleIdentifier');
  const expectedId = 'com.electron.acabox';
  if (bundleId !== expectedId) {
    throw new Error(`Unpacked update has bundle id "${bundleId}", expected "${expectedId}".`);
  }

  const version = await readPlistValue(newBundlePath, 'CFBundleShortVersionString');
  if (version !== expectedVersion) {
    throw new Error(`Unpacked update reports version ${version}, expected ${expectedVersion}.`);
  }

  // Not an identity check (ad-hoc has no identity) — this catches a bundle
  // mangled in transit or unpacking, which would launch to "is damaged".
  try {
    await execFileAsync('/usr/bin/codesign', ['--verify', '--strict', newBundlePath]);
  } catch (err) {
    throw new Error(`Unpacked update failed signature validation: ${(err as Error).message}`);
  }
}

/**
 * The swap itself can't run inside the process being replaced, so it goes to a
 * detached bash script that waits for us to exit first.
 *
 * Ordering is chosen so there is never a moment with no app installed: the old
 * bundle is moved aside (not deleted), and it is only removed once the new one
 * is in place. Any failure rolls back to it.
 */
export function buildSwapScript(): string {
  return `#!/bin/bash
set -u
PID="$1"; TARGET="$2"; NEW="$3"; STAGING="$4"; LOG="$5"
exec >>"$LOG" 2>&1
echo "=== $(date -u '+%Y-%m-%dT%H:%M:%SZ') swap start pid=$PID"
echo "    target=$TARGET"
echo "    new=$NEW"

# Wait up to 60s for the app to exit. If it is somehow still alive we must NOT
# swap — replacing a running bundle is how you get a half-updated app.
for _ in $(seq 1 600); do
  kill -0 "$PID" 2>/dev/null || break
  sleep 0.1
done
if kill -0 "$PID" 2>/dev/null; then
  echo "!!! pid $PID still running after 60s — aborting, install left untouched"
  rm -rf "$STAGING"
  exit 1
fi
sleep 1

BACKUP="\${TARGET}.acabox-old"
rm -rf "$BACKUP"
if ! mv "$TARGET" "$BACKUP"; then
  echo "!!! could not move the old bundle aside — aborting, install left untouched"
  rm -rf "$STAGING"
  exit 1
fi
if ! mv "$NEW" "$TARGET"; then
  echo "!!! install failed — rolling back to the previous version"
  rm -rf "$TARGET"
  mv "$BACKUP" "$TARGET"
  rm -rf "$STAGING"
  exit 1
fi

rm -rf "$BACKUP" "$STAGING"
# The zip was fetched programmatically so it should carry no quarantine flag,
# but strip it defensively — a quarantined bundle prompts on every launch.
xattr -dr com.apple.quarantine "$TARGET" 2>/dev/null || true
echo "swap ok — relaunching"
open "$TARGET"
`;
}

/**
 * Download, verify, stage, and schedule the swap. On success this quits the
 * app and never returns; on failure it throws with a message fit to show the
 * user, having left the installed app untouched.
 */
export async function runSelfUpdate(req: SelfUpdateRequest): Promise<void> {
  const support = await checkSelfUpdateSupported();
  if (!support.ok || !support.bundlePath) {
    throw new Error(support.reason ?? 'Self-update is not available.');
  }
  const bundlePath = support.bundlePath;

  const file = selectUpdateFile(req.files);
  if (!file) throw new Error('Release manifest lists no .zip payload to install.');

  // Mirrors the tag scripts/release.mjs creates (`v<version>`). If that naming
  // ever changes, this URL is the thing that breaks.
  const url = `https://github.com/${req.owner}/${req.repo}/releases/download/v${req.version}/${file.url}`;
  const zipPath = path.join(os.tmpdir(), `acabox-update-${req.version}.zip`);
  // Stage beside the target so the final move is a rename on the same volume,
  // not a 180MB cross-device copy while the user waits at a dead app.
  const stagingDir = path.join(path.dirname(bundlePath), `.acabox-update-${req.version}`);

  const cleanup = async () => {
    await fsp.rm(zipPath, { force: true }).catch(() => undefined);
    await fsp.rm(stagingDir, { recursive: true, force: true }).catch(() => undefined);
  };

  try {
    log.info(`[SELF-UPDATE] Downloading ${url}`);
    const digest = await downloadWithProgress(url, zipPath, file.size, req.onProgress);
    if (digest !== file.sha512) {
      throw new Error('Downloaded update failed its checksum — refusing to install.');
    }
    log.info('[SELF-UPDATE] Checksum OK; unpacking');

    await fsp.rm(stagingDir, { recursive: true, force: true });
    await fsp.mkdir(stagingDir, { recursive: true });
    // ditto, not unzip: it is the only unpacker that reliably preserves the
    // symlinks, resource forks, and permissions inside a .app bundle.
    await execFileAsync('/usr/bin/ditto', ['-x', '-k', zipPath, stagingDir]);

    const newBundlePath = path.join(stagingDir, path.basename(bundlePath));
    await validateNewBundle(newBundlePath, req.version);
    log.info(`[SELF-UPDATE] Staged and validated ${newBundlePath}`);

    const scriptPath = path.join(os.tmpdir(), `acabox-swap-${req.version}.sh`);
    await fsp.writeFile(scriptPath, buildSwapScript(), { mode: 0o755 });
    const swapLog = path.join(app.getPath('logs'), 'update-swap.log');
    await fsp.mkdir(path.dirname(swapLog), { recursive: true }).catch(() => undefined);

    // Detached so it outlives us — we are about to be the process it waits on.
    const child = spawn(
      '/bin/bash',
      [scriptPath, String(process.pid), bundlePath, newBundlePath, stagingDir, swapLog],
      { detached: true, stdio: 'ignore' },
    );
    child.unref();

    log.info(`[SELF-UPDATE] Swap scheduled (pid ${child.pid}); quitting. Log: ${swapLog}`);
    await fsp.rm(zipPath, { force: true }).catch(() => undefined);
    app.quit();
  } catch (err) {
    await cleanup();
    log.error('[SELF-UPDATE] Failed:', (err as Error).message);
    throw err;
  }
}
